In [1]:
import numpy as np

In [9]:
#creation of numpy array
x=np.array([1,2,3,4,5])
print(x)
print(type(x)) #ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#shape  and size
print(x.size)
print(x.shape) #dimension
print(x.ndim) #number of dimensions

5
(5,)
1


In [11]:
x2d=np.array([[1,2,3],[4,5,6]])
print(x2d)
#shape  and size
print(x2d.size)
print(x2d.shape) #dimension
print(x2d.ndim) #number of dimensions

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [12]:
x25=np.random.randint(1,100,(5,5)) #randint(start,stop,size (always in tuple))
print(x25)

[[36 51 40 63 96]
 [80 72 50 38 87]
 [39 99 38 79  7]
 [86 27 69 57 43]
 [85 45 42 47  3]]


In [19]:
xseq1=np.arange(1,101,4)#arange=advanced range
print(xseq1.size,'elements')
print('=>1D MATRIX')
print(xseq1)
print('=>1D MATRIX RESHAPED TO 2D')

print(xseq1.reshape(5,5)) #RETURNS MATRIX OF 5*5


25 elements
=>1D MATRIX
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
=>1D MATRIX RESHAPED TO 2D
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [ ]:
xseq2=np.linspace(1,100,50) #linspace(start,end,number of elements b/w the start and end value)
print(xseq2.size,'elements')
print('=>1D MATRIX')
print(xseq2)
print('=>1D MATRIX RESHAPED TO 2D')
print(xseq2.reshape(10,5))
print('=>1D MATRIX REHSAPED TO 3D')
print(xseq2.reshape(5,5,2))



In [24]:
xseq2d=xseq2.reshape(10,5)
print(xseq2d)

[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.48979592]
 [ 51.51020408  53.53061224  55.55102041  57.57142857  59.59183673]
 [ 61.6122449   63.63265306  65.65306122  67.67346939  69.69387755]
 [ 71.71428571  73.73469388  75.75510204  77.7755102   79.79591837]
 [ 81.81632653  83.83673469  85.85714286  87.87755102  89.89795918]
 [ 91.91836735  93.93877551  95.95918367  97.97959184 100.        ]]


In [28]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing
- boolean filter
- maths and stats
- methods

In [31]:
x25

array([[36, 51, 40, 63, 96],
       [80, 72, 50, 38, 87],
       [39, 99, 38, 79,  7],
       [86, 27, 69, 57, 43],
       [85, 45, 42, 47,  3]])

In [32]:
#first row
print(x25[0])

[36 51 40 63 96]


In [33]:
#last row
print(x25[-1])

[85 45 42 47  3]


In [35]:
print(x25[0,1]) #same as print(x25[0][1]) #for second element of the first row

51


In [40]:
#first column
print(x25[:, 0]) 
#values of 2 value
print(x25[:,1])

[36 80 39 86 85]
[51 72 99 27 45]


In [42]:
#column 0 and 1 index
print(x25[:,[0,1,2]])#[row:,col]
#same
print(x25[:,3])

[[36 51 40]
 [80 72 50]
 [39 99 38]
 [86 27 69]
 [85 45 42]]
[63 38 79 57 47]


In [48]:
#print values below 20
#for i in x25:
 #   for j in i:
  #      if j<=20:
   #         print(j)
   

In [50]:
#filtering data without numpy boolean filter(bad idea)
for i in x25:
    for j in i:
        if j<=20:
            print(j)

7
3


In [51]:
x25<=20 #boolean filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

In [53]:
x25[x25<=20] #will print only the data in the matrix that satisfies the condition written inside it

array([7, 3])

In [56]:
x25[(x25>20)&(x25<70)] # elements greater than 20 but less than 70

array([36, 51, 40, 63, 50, 38, 39, 38, 27, 69, 57, 43, 45, 42, 47])

- *_to append data we use np.append_*



In [58]:
np.append(x25,[1,2,3,4,5])#not gives  answer as expected ,but works

array([36, 51, 40, 63, 96, 80, 72, 50, 38, 87, 39, 99, 38, 79,  7, 86, 27,
       69, 57, 43, 85, 45, 42, 47,  3,  1,  2,  3,  4,  5])

In [70]:
np.append(x25,np.array([[1,2,3,4,5]]),axis=0) #one row of a gieven elements gets added
#[[]]->means 2d array #axis=0 will add data row wise and if axis =1 then data will be added column wise
#since x25 is already a 2d array so we are suppose to give 2d array to be appended


array([[36, 51, 40, 63, 96],
       [80, 72, 50, 38, 87],
       [39, 99, 38, 79,  7],
       [86, 27, 69, 57, 43],
       [85, 45, 42, 47,  3],
       [ 1,  2,  3,  4,  5]])

In [69]:
np.append(x25,np.array([[1],[2],[3],[4],[5]]),axis=1)


array([[36, 51, 40, 63, 96,  1],
       [80, 72, 50, 38, 87,  2],
       [39, 99, 38, 79,  7,  3],
       [86, 27, 69, 57, 43,  4],
       [85, 45, 42, 47,  3,  5]])

In [73]:
a=np.random.randint(1,100,(3,2))
b=np.random.randint(1,100,(2,3))

- # a.transpose and a.T are the same thing

In [74]:
a.T

array([[ 1, 35, 39],
       [59, 25, 22]])

In [76]:
np.hstack((a.T,b))

array([[ 1, 35, 39, 31, 76,  9],
       [59, 25, 22, 31,  5, 15]])

In [78]:
np.hstack((a,b.T))

array([[ 1, 59, 31, 31],
       [35, 25, 76,  5],
       [39, 22,  9, 15]])

In [80]:
print(np.vstack((a,b.T))) # vstack= vertical stack
print(np.vstack((a.T,b)))

[[ 1 59]
 [35 25]
 [39 22]
 [31 31]
 [76  5]
 [ 9 15]]
[[ 1 35 39]
 [59 25 22]
 [31 76  9]
 [31  5 15]]


In [82]:
print(np.hstack((a,b.T))) # hstack= horizontal stack
print(np.hstack((a.T,b)))

[[ 1 59 31 31]
 [35 25 76  5]
 [39 22  9 15]]
[[ 1 35 39 31 76  9]
 [59 25 22 31  5 15]]


- we are not required to apply any loop for adding the matrix ae can simply we can place +

In [2]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print()
print(y)

[[4 9 8]
 [2 3 2]
 [2 3 3]]

[[6 6 5]
 [7 3 1]
 [9 3 9]]


In [3]:
print('add')
print(x+y)
print('sub')
print(x-y)
print('div')
print(x/y)
print('element wise multiplication')
print(x*y)
print('element wise mod')
print(x%y)

add
[[10 15 13]
 [ 9  6  3]
 [11  6 12]]
sub
[[-2  3  3]
 [-5  0  1]
 [-7  0 -6]]
div
[[0.66666667 1.5        1.6       ]
 [0.28571429 1.         2.        ]
 [0.22222222 1.         0.33333333]]
element wise multiplication
[[24 54 40]
 [14  9  2]
 [18  9 27]]
element wise mod
[[4 3 3]
 [2 0 0]
 [2 0 3]]


In [6]:
print(x.dot(y))
print()


[[159  75 101]
 [ 51  27  31]
 [ 60  30  40]]



In [8]:
x.sum(axis=0) #row wise sum

array([ 8, 15, 13])

In [9]:
x.sum(axis=1)#column wise sum

array([21,  7,  8])

In [11]:
print(x.mean())
print(x.mean(axis=0)) #row
print(x.mean(axis=1))#col

4.0
[2.66666667 5.         4.33333333]
[7.         2.33333333 2.66666667]


In [12]:
x


array([[4, 9, 8],
       [2, 3, 2],
       [2, 3, 3]])

In [14]:
print(x.max())#max value
print(x.min())#min value
print(x.argmax())#index of max value
print(x.argmin())#index of min value
print(x.flatten()[4])# accessing the index value givenn by argmax()

9
2
1
3
3


In [15]:
np.median(x) #some function are called using np ,if not available through the variable

3.0


- excel is made of c++
- pandas will do majority of the work
- file is csv becoz file will open on excel . csv means comma separated values. its called csv bcoz ita has comma separated data.
- this can even open in notepad as well in  vscode if u  wnat